# Generated by Django 3.2.8 on 2022-04-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pens', 'pens'), ('caps', 'caps'), ('t_shirts', 't_shirts'), ('cups', 'cups')], max_length=30, verbose_name='Категории')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('remainder', models.BooleanField(default=0, verbose_name='Остаток')),
                ('img', models.ImageField(blank=True, upload_to='product_img', verbose_name='Изображение')),
            ],
        ),
    ]
