# Generated by Django 3.2.8 on 2022-04-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pens', 'pens'), ('t_shirts', 't_shirts'), ('caps', 'caps'), ('cups', 'cups')], max_length=30, verbose_name='Категории'),
        ),
    ]
